### ISSUE TITLE
Renderer non critical bugs

### ISSUE THREAD

**Issue by Aatu** [Aatu/FieryVoid#502] opened 2018-02-13 22:04 UTC
~~Called shots are not working (close though)~~
Combat log should show everything when replay is not on
After replay a destroyed ship might still be visible
Deployment validation is still not working correctly (on standard limited area)
~~Elint actions do not have visual indicators~~
~~Bot panel EW is not updated properly when changing ship or changing power settings~~
~~Zooming close to select ship from hex where there are multiple is too slow. Reimplement the menu to select ship after a click.~~

**Comment by Zero1627** [comment] 2018-02-16 11:50
not a bug per se, rather an idea of new feature:
Currently replay buttons are next/previous turn and move. I think phase would be useful as well (to move straight to firing phase without watching movement mainly ;) ).

**Comment by Zero1627** [comment] 2018-02-16 11:58
also, an important feature missing: clicking on unit in fleet list windows (either one) should move screen to this unit. Currently it does nothing.

**Comment by Aatu** [comment] 2018-02-16 12:11
We have two fleet lists. Can we combine the features of them so that we need only one?

**Comment by Zero1627** [comment] 2018-02-16 15:01
"display EW" shortcuts (E, W) do not work. They are important quality of life things, allowing easy estimation of EW without need to go into every ships' details.

**Comment by Zero1627** [comment] 2018-02-16 15:07
BUG: ship window doesn't have updated EW information.
eg. I change EW, switch ship, come back - bottom left pane has new EW, ship window says I have DEW only...

BUG: blanket DEW not taken into account in onmouseover ship profile.

**Comment by Zero1627** [comment] 2018-02-16 15:11
enhancement request: onmouseover not displayed after selecting something with L-click. I need to click elsewhere to close previous window first. 

I'd say for quality of life it would be better if onmouseover of another ship cancelled previously brought up screen...

**Comment by Zero1627** [comment] 2018-02-16 15:13
Nug: selected ships' EW remains on screen even after ship ceases to be selected, mixing with onmouseover EW (need to select another ship to disappear it).

**Comment by Zero1627** [comment] 2018-02-16 15:21
SCS says EMines were launched. But I do not se launch point marking...

**Comment by Zero1627** [comment] 2018-02-16 15:27
not a bug, but query: tool to check distance between hexes?... (any hexes, not just from one ship to another)

**Comment by Zero1627** [comment] 2018-02-16 18:37
multiple moves forward - hugequality of life improvement.

**Comment by Zero1627** [comment] 2018-02-16 19:54
screen not updated when Yiur move was next (same as on turn start). Updated ok when next move was mine.

**Comment by Zero1627** [comment] 2018-02-17 20:05
I just noticed that remaining thrust in bottom left window is not updated...
in fact, no data is - turn costs stay fixed  on that screen despite speed changes

**Comment by Zero1627** [comment] 2018-02-19 21:16
Mobile-related window prevents mouseover popups to appear - this seriously hurts quality of life on desktop. I must manualy close the window I don't care for and didn't even notice (as I brought my ship up with R-click) to get targeting information...

**Comment by Zero1627** [comment] 2018-02-19 21:52
R-click to bring up all weapons of a given type does not work.

**Comment by Zero1627** [comment] 2018-02-19 22:07
BUG: R-click brings up ship window and brings up appropriate EW window.
L-click on new button brings up ship window but does NOT properly update EW window!

**Comment by Zero1627** [comment] 2018-02-19 22:12
cannot choose from multiple units on hex - have to close to where they do not overlap... it's very good to be able to do so, but bad to have to do so.

**Comment by Zero1627** [comment] 2018-02-21 10:06
I see no information about direction of incoming missile. Eg. I see launch hexes and I get nice informations about incoming weapons, but they are not connected (which is kind of important for setting up interception...)

**Comment by Zero1627** [comment] 2018-02-21 14:39
not a bug, just an improvement to think about: how can CCEW (and perhaps DEW) be made more apparent without need to click on ship?
OEW lines are clear. DEW circle is almost completely invisible. CCEW is almost impossible to see without specifically looking for it at zoom in (which kind of defies the purpose - it's easier to just r-click...).

Perhaps one of these EW forms can get bigger (much bigger, as in expanding at least one hex away) circle? As for the other... Perhaps icon near ship, like a small shield to indicate active DEW? 

Or - as current - just two circles, DEW inner and CCEW outer. But DEEEW itself must reach at least a hex away (for strong DEW anyway), and CCEW must be well visible on top of that (so at least a few more hexes). With multiple ships and possible active BDEW, that may easily get unreadable :( .

**Comment by Zero1627** [comment] 2018-02-21 15:11
reaction on weapon targeting (between click anbd actual weapon marking) is very slow (but not atrociously slow like EW and movement were!)

**Comment by Zero1627** [comment] 2018-02-21 15:15
Perhaps display new buttons closer to top of window?... when trying to fire multiple weapons buttons may lay extremely low (like beyond screen if target isn't positioned near top)

**Comment by Aatu** [comment] 2018-02-21 15:39
This one a bit more critical: calculateBaseHitChange in weaponManager does not seem to take into account BDEW, possibly SDEW and Jinking

**Comment by Zero1627** [comment] 2018-02-21 15:54
Game does not display movement direction! Which may cayuse trouble after pivot...

**Comment by Zero1627** [comment] 2018-02-21 16:00
>This one a bit more critical: calculateBaseHitChange in weaponManager does not seem to take into account BDEW, possibly SDEW and Jinking

Functions are there all right. But they depend on distance counting, perhaps it doesn't work correctly for them?


checking master: jinking is there (lines 680-698), SDEW and BDEW too (703-704)
Now checking three: it's there as well.

**Comment by Zero1627** [comment] 2018-02-21 16:00
checking master: jinking is there (lines 680-698), SDEW and BDEW too (703-704)

Now checking three: it's there as well.

**Comment by Zero1627** [comment] 2018-02-21 16:02
Game does not display movement direction! Which may cayuse trouble after pivot...

**Comment by Zero1627** [comment] 2018-02-21 16:29
turn delay not displayed - at least in Initial Orders phase. 
I mean, the line itself is displayed, but actual value is empty.

**Comment by Zero1627** [comment] 2018-02-24 12:35
I see You changed info available onmouseover, adding EW (and list of incoming ballistic weapons). 

Which is fine, but I think info currently present in master should be incorporated as well l(eg. Ini roll and Ini modifier).

**Comment by Zero1627** [comment] 2018-02-27 20:51
no idea why, but on R-click browser menu opens (besides desired action). In older interface there is no such side effect.

**Comment by Zero1627** [comment] 2018-02-27 21:01
destroyed ship is still displayed (at least after reactor destruction

**Comment by Zero1627** [comment] 2019-09-13 09:11
I am taking liberty of closing this issue.

**Closed by Zero1627** 2019-09-13 09:11 UTC
Labels: bug
