### ISSUE TITLE
New Feature: Add the ability to enable or disable optional rules

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#140] opened 2016-01-11 04:53 UTC
We should implement a few check boxes on the new game screen (and the underlying code to support them obviously) for enabling or disabling some optional rules.

My two examples would be enforcing the power down of Jump engines or disabling optional rules such as called shots.  Both of these should be relatively easy to implement in the code.  

As a longer term idea, perhaps we can have the fleet builder enforce tournament rules for the actual fleet if the option "Tournament Fleet" was enabled in the new game.

**Comment by AncientSion** [comment] 2016-01-11 08:42
I remember Jasper had a similar suggestion back when i enabled the purchasing of flights with a size of more than 6.

Personally im wondering if we really need the option to disable such rules. Called shots are used so rarely, i would bet the average game likely has  less than one. I could run a database query to check it out :p
I dont how many more "optional" rules we are currently utilizing.

Jump Engines: Do you mean the ability to shut down engines even if they are undamaged ? Like you did in our test match ? Or what is this about ?

Tournament fleet: great idea that has been coming up for a long time.
However, considering we arent able to finish the alteration of the existing factions when it comes to the hitArray, i see only a slim chance for properly working tournament-restriction GUI features, because those, without a doubt, would also need slight adjustments (rares and uncommons would require a new variable to indicate what the base class is).

**Comment by tksolway** [comment] 2016-01-11 15:12
Do we have any sort of indication in the log that a called shot has been used?  It is an optional rule, since we are ostensibly using tournament rules for our games then it shouldn't be used at all, regardless of its rarity.

**Comment by AncientSion** [comment] 2016-01-11 16:06
There is one indicator which would be the greatly used hit chance.
It would be trivial to add in a special line if a certain shot was a called shot, but thats not what you want.

Why do you think under tournament rules a called shot should not be allowed ? Its listed in the offical ruleset, so i guess its a matter of context if a specific tournament allows the use of this optional rule or not, and that optional rule or not.

If you really want to add in checkboxes to create games under x, y, z different standards it would, in my eyes, be a change for the worse, because there would be no standard whatsoever.
Also, called shots are implemented since the very days of FV and there was no issue about this yet.

Im all for changes, but in my eyes, specificly this one would be step backwards. The code is there, the feature itself is not just someones imagination, but its in the kitchen sink. I would be a wasted opportunity to cut it from my point of view. 
However, if more people (...) are for it, i would do it sure thing,.

**Comment by tksolway** [comment] 2016-01-11 16:41
http://www.agentsofgaming.com/b5wtourn.htm

"Other than those listed above, no optional rules will be used. Note that this includes ramming (not allowed), ship enhancements (not used), or any other rule listed as an "alternative" or "option." Note also that critical hits are NOT an optional rule, and will be used in the tournament!"

-----

I think it would help with interpersonal conflict to have it codified.  At the moment, we are relying on player adherence to house rules that are not well understood.  For instance, in my game with Marcin he was unhappy about my disabling my Jump Drive.  I was under the impression it was not a tournament rules game because we weren't playing with tournament fleets.  After which, he annoyed me by using called shots in a game that was now "tournamenty?".  I think its better to have the rules laid out to start with and then no one has to argue about what should or shouldn't be adhered to.

**Comment by tksolway** [comment] 2016-01-11 16:43
To begin with perhaps we just need text based notification, perhaps in the game info screen, regarding the rules we expect to be in force.  Actual engine based enforcement can come later.

**Comment by AncientSion** [comment] 2016-01-11 19:21
Its funny, i was kinda surprised when you disabled your jump engines in our test match, but i didnt mind, because, well, test match.
If it would have been a serious skirmish or tournament match, i would requested you to enable them, because especially with the WS, its a serious thing because the ships was designed in a way that would force you to disable NL, Jammer or all MPs.

In general, i think our community is, for some unknown reason, really, really, small - If not tiny.
It would be a very sad day if we annoy or harass each other because of seamingly minor differences. I dont want anyone to hold a grudge when we are only 8 ppl to begin with.

**Comment by tksolway** [comment] 2016-01-11 19:46
That somewhat leads into my point though.  The match I'm referring to with Marcin was as far as I understood a test match.  When is it acceptable to do this or that?  If I'm creating a game, generally I don't care, unless I'm playing a tournament fleet, how do I get that across?  Obviously Marcin wants the Jump Engine followed, but also wants to be able to use called shots.  Everyone has different preferences and I'd rather it all be out in the open when a game starts.  I can't count how many times I've sat at a new game screen with a value other than 3500 pts and wondered, does he want tournament rules followed for the fleet though?  Just had an issue with Onefromb5.  The game he made was 3535 pts, and he was annoyed I didn't bring a tournament legal fleet.  

Even if we don't have the engine enforce these rules, having them listed at a new game screen, and in the game info afterwards will make it clear to everyone what's expected.  That can only be helpful, especially with new players.

**Comment by AncientSion** [comment] 2016-01-11 20:12
new players, right.

Ill look into at least the "tournament legal fleet pls" comment/icon/note, for now.

**Comment by tksolway** [comment] 2016-01-11 20:21
I've seen at least half a dozen new players come and go over the last few months.  If we can get one or two to stay by making things easier for them we'll be better off in the long run.

**Comment by Zero1627** [comment] 2018-09-21 11:20
ability is essentially added - there is fixed map, there is block movement option.
But every option would have to be appropriately coded in places...

**Comment by Zero1627** [comment] 2021-10-05 06:11
as the option does technically exist, I'm closing the thread.

**Closed by Zero1627** 2021-10-05 06:11 UTC
