### ISSUE TITLE
Markab

### ISSUE THREAD

**Issue by tksolway** [Aatu/FieryVoid#162] opened 2016-04-11 17:42 UTC
I've looked into the Markab, and we could do a limited implementation of them to support the campaign.  The Stun gun is a complete no go.  The implementation of that would be a long arduous process.  That being said.  The scatter gun can be implemented as a pulse weapon (it would only lose the ability to hit multiple targets with it's 1d6 shots) and the Plasma Wave should be easy to implement exactly as it works.  Other than that they don't have any special weapons or rules I know of.  

Ships that mount the Stun Gun would have to be ignored, or we would have to agree on custom versions for the campaign that replace/remove them.

**Comment by Zero1627** [comment] 2016-04-12 09:18
Scattergun as a pulse weapon (2d6 pulses hit, 12 maximum, no volley count bonus) should work as intended except capacity to fire at multiple targets, just as You say (I suggest to increase its Intercept rating to compensate).

Stun Beam: I think it can be implemented close enough.
 - vs fighters: just as EP Gun 
 - vs ships: it's possible to make critical last only a given amount of time, right? So it should be doable this way. If not, I'd say burst beam effect (disable for a turn or force critical roll) seems close enough (way from perfect, but still)

When You're thinking about new races, I looked at Denteth, too (Wolfgang mentioned their OSATs multiple times). They seem to require one new feature: LCVs. Do You think they can be implemented?
They would require ability to jink like fighters, and have 'permanent critical' not allowing them to use more than 2 points of DEW (perhaps their Sensors could default to CCEW?).). 
New systems:
Drive: do it as usual, but make Thrusters unhittable
Control: do it as usual, but make C&C unhittable
Reactor loss does not kill the ship: we may live without this feature I'd say

...and of course new layout - essentially MCV but with fire allocation pointing straight to PRIMARY (this would prevent called shots vs non-weapons, btw; would not prevent them vs thrusters, but give them armor value of 150 and people will get the idea :) )


...and new layout, which would be just like OSATs...

**Comment by tksolway** [comment] 2016-04-12 14:09
I've already started implementing the Scatter Gun, you can see it in the Markab branch.  I've altered the fire a bit so that it rolls for each of the 1d6 pulses from the scatter gun (otherwise we would still only have one roll for all six possible pulses).  I think that's a pretty big thing to take into account.  One of it's main advantages over a pulse weapon is that it has a great chance of hitting with some of it's pulses while a pulse weapon is generally all or nothing.  

For now I've implemented the Stun Beam as the Burst Beam with the Stun Beam's Range, fire control and cycling.  I'm going to look into building it properly as well as eventually I want to implement the Rad Cannon too.  

The LCVs are linked to my idea for Medium ships which I still need to work on.

There are a bunch of Medium ships that we've altered to fit them into how the game does medium ships.  My next project after the Markab is going to a Medium ship revamp.  For this I will build medium ships with only one section (Primary) but still maintain the three section hit chart.  This way we can have medium ships function as initially intended.  So all systems on a medium ship will be primary, but they can only be hit based upon where they show up in the hit chart.  Obviously this wasn't possible before we Implemented hit charts.  

The great thing, is if I implement this, LCVs are simply an extension of that (besides their special rules) the only have primary, and only one hit chart.  So we could definitely look into them afterwards.

**Comment by Zero1627** [comment] 2016-04-12 20:11
>I've already started implementing the Scatter Gun, you can see it in the Markab branch. I've altered the fire a bit so that it rolls for each of the 1d6 pulses from the scatter gun (otherwise we would still only have one roll for all six possible pulses).

Great!

>ne of it's main advantages over a pulse weapon is that it has a great chance of hitting with some of it's pulses while a pulse weapon is generally all or nothing.
Disagreed, Pulse weapons usually do some hits regardless of grouping bonus. Eg. Pulse Cannon family does d5 hits always (average about half of max, but maximum of that is 5/6 - almost everything). So I do not see that as an advantage at all. 

>For now I've implemented the Stun Beam as the Burst Beam with the Stun Beam's Range, fire control and cycling.

I think it's good as quick solution. If Youll manage better  later then good, but I'd say this is good enough.
Exception: You should get rid of power drain ;)


>The great thing, is if I implement this, LCVs are simply an extension of that (besides their special rules) 

besides special rules (jinking and EW allocation), LCVs can be well implemented as is. All their systems are on PRIMARY anyway, just make outer hit charts consist of one entry: 20->PRIMARY. It should work as advertised.

As for Your MCV approach: I'll read it in detail later tonight, and then comment.

**Comment by Zero1627** [comment] 2016-04-12 20:20
>There are a bunch of Medium ships that we've altered to fit them into how the game does medium ships. My next project after the Markab is going to a Medium ship revamp. For this I will build medium ships with only one section (Primary) but still maintain the three section hit chart. This way we can have medium ships function as initially intended. So all systems on a medium ship will be primary, but they can only be hit based upon where they show up in the hit chart. Obviously this wasn't possible before we Implemented hit charts.

I can't comment on this because I don't understand how it wll work. I thought You give explanation elsewhere, but it seems other thread points here :)

What I wanted to do is to add ability to do entries like PRIMARY:SYSTEMNAME, indicating that system instance should be looked for on PRIMARY. Called shots vs such systems would not be possible, but it should allow PRIMARY systems to show up on outer hit tables - which I think would solve all problems except called shots.

**Comment by tksolway** [comment] 2016-04-12 20:38
Sorry, I typed that out in a hurry let me do a better explaination.  I'll post a new issue for it.

**Comment by Zero1627** [comment] 2016-11-14 08:08
Deneth done. LCVs can't jink (his was deleted from final rules?) and their sensors are the usual ones (to be changed, there's a separate thread for that).

>What I wanted to do is to add ability to do entries like PRIMARY:SYSTEMNAME

...and this one is complete.


but thread itself is about Markab, so I leave it be ;)

**Comment by tksolway** [comment] 2017-04-07 16:03
Long ago I started working on the Markab.  I got stalled trying to get some of their weapons to work.  Obviously you guys have had great success in creating new weapons.  

If you could implement the two or three weapons that the Markab need, I'd be happy to build the SCSs to get them out there.

**Comment by Zero1627** [comment] 2017-04-10 07:19
tell me which ones You want, and I'll see what I can do :)

**Comment by tksolway** [comment] 2017-04-10 14:35
We would need the stun gun, the scatter gun and the plasma wave.

Wolfgang and I had talked about the stun gun just being re-implemented as Burst Beam, which I think is already in game.  Here are the relevant comments.  

"I notice that the Streib are implemented in the back end of the game, although not available to players.   Not sure if they ever got around to doing the Electro Burst Beam or the medium burst beam.  If they did it might be a good replacement.  Otherwise I'm sure we can figure out something to give the scout in that place.  Let me look into the getting them built.  I doubt whether anyone will have too much of a problem with the scatter-gun limitation, how many times do you really want to split your fire in game anyway?

edit
On second thought, If the burst beam is implemented, I could build a new weapon around it with the same Fire control and Range profile as the Stun gun, it wouldn't function exactly like the stun gun, but pretty close.  And it wouldn't be too strong (with the medium burst beam) or too short ranged (with the burst beam). "

I had played around with trying to implement the scattergun as an advanced pulse weapon.  Technically per the rules, the scattergun should roll for the number of shots, and then do a to hit roll for each shot.  Giving it a less swingy damage output.  I'm not sure if this can be done, but you can find my meager attempts in the Markab branch that is still hanging around here.  

If we can get those three weapons built I can implement the SCSs with some default images to support the campaign.

**Comment by Zero1627** [comment] 2017-04-10 15:41
Stun beam: I vaguely remember discussing it with You, too, with similsar conclusion that Burst Beam would be a good base. I do not remember details though. Will look into and implement something.

Scattergun: this one proved difficult. In fact I have already implemented it, but in rudimentary fashion that loses lots of flavor (what I got can be just called Triple Array, really).

Plasma Wave: that seems to just be a torpedo that does variable Flash damage, I do not expect much trouble, will do.

**Comment by tksolway** [comment] 2017-04-10 19:53
Ya, I'd always thought the Scattergun would be hardest.  Because the game rolls before it really takes weapon into account.  What I was trying in the Markab branch wasn't really working.  I'd thought later that we might do something where a shot is taken and it generates 1dx additional shots at that target.  I'm sure we couldn't have it hit multiple targets with it's shots, that would be way to difficult.

**Comment by Zero1627** [comment] 2017-04-11 07:39
generating random number of Pulses would have been easy, but random number of shots was a killer. That would require LOTS of changes, and I opted against it. Similarly forcing interception of different shots is not present.

Overall it's a weapon of appropriate power, but the flavor of highly random 'scatter' weapon is lost.

**Comment by tksolway** [comment] 2017-04-11 13:52
That's fair, and I think Wolfgang is fine with that compromise.  Thanks for taking this on, let me know what the Class names for the weapons will be and I will start the ship SCSs

**Comment by Zero1627** [comment] 2017-04-11 13:54
sure I will - when they're done. I'll try to do them relatively quickly, but as for now RL knocks hard (and I already promised Wolfgang to finish Drakh ;) ).

**Comment by tksolway** [comment] 2017-04-11 13:58
NP, thanks.

**Comment by Zero1627** [comment] 2017-05-19 14:22
Your weapons are ready, and can be reviewed installed on Target Drone (custom ships) - https://github.com/Aatu/FieryVoid/blob/master/source/server/model/ships/customs/technicalTargetDrone.php

Note that Plasma Wave and Stun Beam don't yet have icons - I assume You'll do them better than me :) .

Also note that all weapons have pre-set Power and Structure values and will use them if You set 0 in creator call (so You don't have to remember what the correct values should be, but still can override if You want to for any reason).

Weapon notes:
Plasma Wave: should work as advertised, not tested.
Stun Beam: works as poor man's Burst Beam (kills fighters and disables powered systems, but doesn't cause criticals), not tested.
Scattergun: always uses 3 separate shots - so it's effectively a triple array rather than any kind of 'scatter' weapon... but works ;)

**Comment by tksolway** [comment] 2017-05-19 16:36
Thanks Marcin,

I will take a look at these this weekend.

**Comment by Zero1627** [comment] 2017-05-22 07:49
Note that I'm considering boosting Stun Beam a bit as compensation for lost abilities... Eg. increasing RoF to 1/turn would make it significantly better weapon (still not as good as it was vs ships, but even better vs fighters - which should give appropriate power level overall). What's Your opinion?

**Comment by tksolway** [comment] 2017-05-22 14:37
I think the change in the weapon profile (the fire control and the range penalty) help it be a better weapon anyway.  It’s actually a rather long range anti-fighter weapon as it is.  There really isn’t too much difference between the two rules wise as they both force you to shut down systems.  The burst beam is a tiny bit better as it reduces power when it hits structure.  The Stun beam was ineffective against structure.

**Comment by tksolway** [comment] 2017-05-22 21:10
Hey, 

It looks like I need a fighter weapon for them as well, the light scattergun.  It is 2d6 at 1d3 shots.  What do you think of just setting it as 2d6 with two shots?

**Comment by Zero1627** [comment] 2017-05-23 10:44
>I think the change in the weapon profile (the fire control and the range penalty) help it be a better weapon anyway.  It’s actually a rather long range anti-fighter weapon as it is.  There really isn’t too much difference between the two rules wise as they both force you to shut down systems.  The burst beam is a tiny bit better as it reduces power when it hits structure.  The Stun beam was ineffective against structure.

I compare with Stun Beam as in the rules, not with Burst Beam. Original Stun Beam soesn't cause crits or power loss, but on a few crucial systems (like Sensors) does have nasty temporary effects.
Well, of course now that I simplified to forced shutdown of all powered systems said sensors would have even nastier temporary effect of course ;) - so maybe indeed just leave it as is.

Fighter weapon: if we give them fixed intercept rating (-2 I think), random number of impacts is not a problem at all. I'll just call it Pulse weapon, d3 shots, no grouping bonus ;) . Will prepare such weapon when time allows (hopefully soon).

**Comment by Zero1627** [comment] 2017-05-23 14:10
I have made some corrections (mainly splitting fightes into old and new variant), merged with master and uploaded to test environment.

I have tested how everything loads and looks on ship selection screen - looks good.
I have NOT actually tested them in game. I will do so when time permits, or You may do it at Your leisure (below address of test instance).
http://54.195.156.116/marcin_test/FieryVoid/source/public/games.php

I've noted that Stun Beam and Plasma Wave icons do look strange - please do check.

Also, early Drofta is mighty costly for its capabilities! Not that new one is much better, but at least it has a gun capable of actually dealing damage... as soon as thrust 7 fighter gets in position to fire at something...

**Comment by Zero1627** [comment] 2017-05-23 14:11
didn't mean to close, just send my answer to You!

**Comment by tksolway** [comment] 2017-05-23 14:35
Yarr, their fighters are not great ☺

It looks like the images have some issues with how I made the background transparent, I’ll see if I can fix that.

**Comment by tksolway** [comment] 2017-05-23 14:46
Ran a test game with them, the weapons all seem to work as expected.  I’ll need to see what I can do bout images for the ships and cleaning up the two weapon images.

**Comment by Zero1627** [comment] 2017-05-25 15:27
After some thought, I am thinking about remodeling Scattergun, too.

Current: 3 separate shots, -1 interception each (should be -2, my mistake!)
Proposed change: 1 shot (Pulse mode with d6 impacts, no grouping bonus), interception -3.

Main advantage of proposed change: I think this would catch Scattergun feeling much better than current 'triple array' iteration.

It has a bit better intercept rating vs single shot than it should, but much worse overall intercept rating. Also, it's quite easily intercepted itself (but it doesn't matter all that much for a light weapon). And d6 shots do catch Scatter spirit, I think...
What's Your opinion?

**Comment by tksolway** [comment] 2017-05-25 19:16
I think that would be perfect.  That is much what I was originally trying to implement.

**Comment by Zero1627** [comment] 2017-05-26 11:05
I will do it then :) . That will have no impact on usage of the weapon, so You may just go on with Your part :)

**Comment by Zero1627** [comment] 2017-06-07 10:33
ScatterGun rebuilt, changes deployed. 

Can You use images Onefromb5 found to create Markab silhouettes? They're less detailed, but I'd say good enough (just resize and add appropriate background) - better than reusing EA ships?

**Comment by tksolway** [comment] 2017-06-07 15:33
It is better, I’m not sure when I’ll have time to do it though.  This weekend is busy.

**Comment by Zero1627** [comment] 2017-06-08 08:01
'not soon' is way better than 'never' :)

**Comment by Zero1627** [comment] 2017-06-23 08:13
Adding Markab images provided by Wolfgang - and closing issue.

**Closed by Zero1627** 2017-06-23 08:13 UTC
Labels: enhancement
